# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board01',
            new_name='Contacts',
        ),
    ]
