# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer03',
            name='state',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
