# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170423_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer03',
            name='state',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
