# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170424_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer03',
            name='state',
        ),
        migrations.AlterField(
            model_name='customer03',
            name='end_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer03',
            name='start_date',
            field=models.IntegerField(),
        ),
    ]
