# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20170413_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer04r',
            name='title',
        ),
        migrations.AddField(
            model_name='customer04',
            name='writer',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer04r',
            name='content',
            field=models.TextField(),
        ),
    ]
