# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20170503_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer04a',
            name='customer04q',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer04q'),
        ),
        migrations.AlterField(
            model_name='customer04a',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer04a',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
