# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0006_auto_20170413_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer04r',
            name='user',
        ),
        migrations.RenameField(
            model_name='customer04',
            old_name='writer',
            new_name='password',
        ),
        migrations.AddField(
            model_name='customer04',
            name='content',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customer04',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer04r',
        ),
    ]
