# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20170414_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer03',
            name='end_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer03',
            name='start_date',
            field=models.CharField(max_length=20),
        ),
    ]
