# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20170419_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer03',
            name='state',
            field=models.BooleanField(default=2),
            preserve_default=False,
        ),
    ]
