# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer03_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer03',
            name='state',
            field=models.NullBooleanField(default=True),
        ),
    ]
