# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20170419_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer03',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
