# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsel01',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media/%y/%m/%d'),
        ),
    ]
