# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsel02',
            old_name='time',
            new_name='endtime',
        ),
        migrations.AddField(
            model_name='counsel02',
            name='starttime',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='counsel02',
            name='birth',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='counsel02',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
