# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0002_auto_20170416_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsel02',
            name='agree',
            field=models.CharField(max_length=10),
        ),
    ]
