# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0003_auto_20170412_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsel02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=20)),
                ('fp', models.CharField(max_length=15, null=True)),
                ('content', models.CharField(max_length=50, null=True)),
                ('agree', models.BooleanField()),
                ('birth', models.DateField()),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('address', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=10, null=True)),
                ('time', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
